services:
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=grupo2arquitectura
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  postgres-data:
  mongo-data:

networks:
  app-network:
    driver: bridge
